remote_theme: pmarsceill/just-the-docs
title: adastaking.ch
aux_links:
  "Cardano":
    - "https://cardano.org/"
ga_tracking: G-VCF6QWJQLV
collections:
  pool:
    permalink: "/:collection/:path/"
    output: true
  beginners:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    pool:
      name: Der HELVX Pool
    beginners:
      name: Beginner