remote_theme: pmarsceill/just-the-docs
title: adastaking.ch
aux_links:
  "Cardano":
    - "https://cardano.org/"
ga_tracking: G-VCF6QWJQLV
collections:
  pool:
    permalink: "/:collection/:path/"
    output: true
  cardano:
    permalink: "/:collection/:path/"
    output: true
  glossar:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    pool:
      name: Der HELV* Pool
    cardano:
      name: Cardano / ADA
    glossar:
      name: Glossar